_core:
  default_config_hash: MymgTM4i959vZLJ3F-hpn_ntX-johso5eQqRm-03r0Y
include_invalid_paths: false
excluded_paths: ''
include_home_segment: true
home_segment_title: Home
include_title_segment: true
title_from_page_when_available: true
title_segment_as_link: false
segments_separator: null
use_menu_title_as_fallback: false
remove_repeated_segments: true
language_path_prefix_as_segment: false
