access_token: 1055556756-2HgKhmWFEBgBDKGs0ylS3ey4kvzucLKZgfoUHGF
access_token_secret: 1ORxi0v2ugU0EPLALZu60i4SOCmBi6DnYnBMrgqD2PRUz
twitter_api_consumer_key: rRNWjkwQc3rycyJsHaC7Z8ea1
twitter_api_consumer_secret: L4cC2gQ07DQUVVrZimdgDwPDRahGxWXjVaUCo6LT7UKXzHJJhi
consumer_key: ZoZWqTr530sEHYtqIsoFXr7S1
consumer_secret: cY5Xje61dfkpOg219Uk6zZ3nJwMERSSFzcjj71kRT9p0Eb4fJz
facebook_url: 'http://www.facebook.com/maseniorcare'
twitter_url: 'http://www.twitter.com/maseniorcare'
