netforum_event_sync:
  event_types: ''
_core:
  default_config_hash: E_EkA1Op1lL97ZbB9WaBAfdWrJ8ZVkUTAPSgOIoDoVE
event_types: "Committee\r\nConference\r\nEducation\r\nFundraising\r\nMembership\r\nPublic\r\nSEMINAR\r\nseminar\r\nSeminar\r\nSocial\r\nWebinar"
