_core:
  default_config_hash: AyT9s8OUcclfALRE_imByOMgtZ19eOlqdF6zI3p7yqo
langcode: en
uuid: 2bbf38cd-002f-4af0-af7e-903aa0b8b3fe
name: 'Mass Senior Care Foundation'
mail: jordan@handsomedogstudio.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
