<?php

/**
 * @file
 * Contains real_magnet.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function real_magnet_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the real_magnet module.
    case 'help.page.real_magnet':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Send newsletter node content to Real Magnet service.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function real_magnet_page_attachments(array &$page) {
  // If user doesn't have permissions or it's not a node, no point doing anything.
  if (!\Drupal::currentUser()->hasPermission('access contextual links')) {
    return;
  }
  if (\Drupal::routeMatch()->getParameter('node')) {
    // If user has permissions and current page is a node.
    $page['#attached']['library'][] =  'real_magnet/hide_tab';
  }
}

/**
 * Implements hook_preprocess_node().
 */
function real_magnet_preprocess_node(&$variables) {
  $variables['base_path'] = $_SERVER['SERVER_NAME'];
}