<?php

/**
 * @file
 * Contains real_magnet.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function real_magnet_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the real_magnet module.
    case 'help.page.real_magnet':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Send newsletter node content to Real Magnet service.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_node().
 */
function real_magnet_preprocess_node(&$variables) {
  $variables['base_path'] = $_SERVER['SERVER_NAME'];
}