<?php
// Include acquia cloud settings.
if (file_exists('/var/www/site-php')) {
  require '/var/www/site-php/msca/foundation-settings.inc';
}
// Include the default settings file.
require $app_root . '/sites/settings.common.php';
// Enable the foundation config split.
$config['config_split.config_split.foundation']['status'] = TRUE;

// <DDSETTINGS>
// Please don't edit anything between <DDSETTINGS> tags.
// This section is autogenerated by Acquia Dev Desktop.
if (isset($_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR']) && file_exists($_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] . '/cld_devcloud_msca_dev_foundation.inc')) {
  require $_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] . '/cld_devcloud_msca_dev_foundation.inc';
}
// </DDSETTINGS>
