name: msca
# add in the varnish edge
proxy:
  edge:
    - msca.acquia.lndo.site
    - foundation.acquia.lndo.site
# start with basic lamp recipe
recipe: drupal8
config:
  php: 7.1 # or other as appropriate
  # modify webroot sub dir as needed
  webroot: docroot
  database: mysql:5.7
  xdebug: true
# add additional auxiliary services
services:
  edge:
    type: varnish:4.1
    backends:
      - appserver
    ssl: true
  cache:
    type: memcached:1.5.12
  foundation_db:
    type: mysql
    portforward: true
    creds:
      user: drupal8
      password: drupal8
      database: foundation
