name: msca
recipe: drupal9
config:
  php: '8.0'
proxy:
  appserver:
    - msc.lndo.site
    - foundation.lndo.site
# add additional auxiliary services
services:
  appserver:
    webroot: docroot
    xdebug: true
    config:
      php: .vscode/php.ini
  msc:
    type: mysql:5.7
    portforward: 3307
  foundation:
    type: mysql:5.7
    portforward: 3308
  cache:
    type: memcached:1.5.12
