<?php

/**
 * @file
 * Contains msca_theme_tweaks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function msca_theme_tweaks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the msca_theme_tweaks module.
    case 'help.page.msca_theme_tweaks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Tweaks for the MSCA Theme') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_view().
 * @todo: put this in the theme itself.
 * This was done in haste because I wasn't able to get it to work in the .theme
 * file, but that's where it should live.
 */
function msca_theme_tweaks_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if($view_mode == 'homepage' && !empty($build['field_date'][0]['#markup'])) {
    $timestamp = $build['field_date'][0]['#markup'];
    $build['month'] = [
      '#markup' => date('M', strtotime($timestamp)),
      '#theme' => 'string',
    ];
    $build['day'] = [
      '#markup' => date('j', strtotime($timestamp)),
      '#theme' => 'string',
    ];
  }
  // We need a rather complexly formatted, short version of addresses for display
  // on the education and events content type.
  if($view_mode == 'full' && isset($build['field_location']['#bundle']) && $build['field_location']['#bundle'] == 'education_events') {
    // Build a short address. Note that these always exist of the field as a
    // whole is not empty (which we check for above).
    $build['short_address'] = [
      '#markup' => $build['field_location'][0]['address_line1']['#value'] . ', '
        . $build['field_location'][0]['locality']['#value'],
      '#theme' => 'string',
    ];
  }

  // On the Recent News view on the homepage, if no teaser image is loaded,
  // increase the length of the text summary to make up for all the white space.
  if($view_mode == 'homepage' && empty($build['field_news_teaser_image'][0])) {
    $build['body'][0]['#text_summary_trim_length'] = 600;
  }


  if($view_mode == 'teaser' && $entity->getType() == 'facility') {

    // Facility websites are stored as text for some reason, so this converts them to a link
    $website_field = $entity->get('field_customer_web_site');
    if(!$website_field->isEmpty()) {
      $uri = $website_field->getValue()[0]['value'];
      if (!\Drupal\Component\Utility\UrlHelper::isValid($uri, TRUE)) {
        $parsed = \Drupal\Component\Utility\UrlHelper::parse($uri);
        if (empty($parsed['scheme'])) {
          $uri = 'http://' . $uri;
        }
        else {
          $uri = FALSE;
        }
      }
      if ($uri) {
        $link = Link::fromTextAndUrl(t('Click Here'), Url::fromUri($uri));
        $build['facility_link'] = $link->toRenderable();
      }
    }
  }
}

/**
 * Implements hook_preprocess_page().
 */
function msca_theme_tweaks_preprocess_page(&$vars) {
  // Sets year and text for copyright to use in footer
  $vars['footer_date'] = t("&copy; Copyright @year, All Rights Reserved",
    [
      '@year' => date('Y'),
    ]
  );
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function msca_theme_tweaks_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $form_state->get('view');
  if ($view->id() !== 'preferred_vendors') {
    return;
  }

  // Change the placeholders
  $form['title']['#placeholder'] = t('Vendor Name');
  $form['field_all_services_target_id']['#options']['All'] = t('Filter by Service');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function msca_theme_tweaks_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Change the label
  $form['name']['#title'] = t('E-Mail Address');
}
