# Schema for the configuration files of the MSC YourMembership Soap module.
msc_ym_soap.settings:
  type: config_object
  label: 'MSC YourMembership Soap settings'
  mapping:
    example:
      type: string
      label: 'Example'
