<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Primary module hooks for MSC Layouts module.
 */

function msc_layouts_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Check if you're dealing with the specific content type that uses layout_paragraphs.
  $lp_types = [
    'paragraph_assembler'
  ];
  // If the form is for a node and the node type is in the array of types that use layout_paragraphs.
  if ($form_id == 'node_paragraph_assembler_edit_form' && in_array($form_state->getFormObject()->getEntity()->bundle(), $lp_types)) {
    // Loop through paragraphs and adjust #required property.
    $layout = $form['field_paragraph']['widget']['layout_paragraphs_builder']['#layout_paragraphs_layout'];
    $paragraphs = $layout->getEntities();
    foreach ($paragraphs as $delta => $paragraph) {
      // Does the rendered $paragraphs_item contain a form?
      $merp = 'derp';
      // Does $paragraphs_item contain a value in field_block_to_embed?
      $values = $paragraph;



    }
  }
}

// if (isset($paragraph_item['subform'])) {
//   // Conditionally adjust #required based on your logic.
//   $form['field_paragraph']['widget'][$delta]['subform']['your_form_element']['#required'] = FALSE;
// }
