<?php

/**
 * @file
 * Contains apitools_test.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function apitools_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the apitools_test module.
    case 'help.page.apitools_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('API Tools Test') . '</p>';
      return $output;

    default:
  }
}
