<?php

/**
 * @file
 * Contains netforum_org_sync.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function netforum_org_sync_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the netforum_org_sync module.
    case 'help.page.netforum_org_sync':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Syncs both Facilities and Preferred Vendors from Mass Senior Care&#039;s NetForum account') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_cron().
 */
function netforum_org_sync_cron() {
  $form = \Drupal::formBuilder()->getForm('Drupal\netforum_org_sync\Form\OrganizationSyncForm');

}