<?php

/**
 * @file
 * Contains netforum_org_sync.module.
 */

use Drupal\netforum_org_sync\OrgSync;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function netforum_org_sync_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the netforum_org_sync module.
    case 'help.page.netforum_org_sync':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Syncs both Facilities and Preferred Vendors from Mass Senior Care&#039;s NetForum account') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_cron().
 */
function netforum_org_sync_cron() {
  /** @var \Drupal\Core\State\StateInterface $state */
  $state = \Drupal::service('state');
  try {
    $current_time = \Drupal::time()->getRequestTime();
    $last = $state->get(OrgSync::CRON_STATE_KEY);
    if (!$last) {
      $last = strtotime('-3 weeks');
    }
    /** @var \Drupal\Core\Datetime\DateFormatterInterface $formatter */
    $formatter = \Drupal::service('date.formatter');
    $count = \Drupal::service('netforum_org_sync.org_sync')->syncOrganizationChanges($last, $current_time);
    $state->set(OrgSync::CRON_STATE_KEY, $current_time);
    \Drupal::logger('netforum_org_sync')->notice('Synced @count organization changes from @start to @end',
      ['@start' => $formatter->format($last), '@end' => $formatter->format($current_time), '@count' => $count]);
  }
  catch (Exception $exception) {
    watchdog_exception('netforum_org_sync', $exception, 'Unable to sync events during cron.');
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * For facility nodes, set field_ge coordinates in presave.
 *
 * @param Drupal\Core\Entity\EntityInterface $entity
 * @return void
 */
function netforum_org_sync_node_presave(EntityInterface $entity) {
  switch ($entity->getType()) {
    case 'facility':
      if  (!empty($entity->field_ge->value) && $entity->field_ge->value !== '0, 0') {
        return;
      }

      \Drupal::service('netforum_org_sync.geocode')->setCoordinates($entity);
      break;

    case 'vendor':

      $fields = [
        'field_primary_services',
        'field_additional_services',
      ];
      $service_ids = [];
      foreach ($fields as $field) {
        foreach ($entity->$field as $key => $service) {
          $service_ids[] = $service->target_id;
        }
      }
      $entity->set('field_all_services', $service_ids);
      break;

    }

}
