<?php

use Abraham\TwitterOAuth\TwitterOAuth;

/**
 * @file
 * Contains msca_tweet_block.module.
 */

/**
 * Implements hook_cron().
 */
function msca_tweet_block_cron() {
  $config = \Drupal::config('msca_tweet_block.settings');

  $access_token = $config->get('access_token');
  $access_token_secret = $config->get('access_token_secret');
  $consumer_key = $config->get('consumer_key');
  $consumer_secret = $config->get('consumer_secret');


  try {
    // Connect to twitter API with our account info
    $connection = new TwitterOAuth($consumer_key, $consumer_secret, $access_token, $access_token_secret);

    $tweets = $connection->get('statuses/user_timeline', [
      'screen_name' => 'maseniorcare',
      'count' => 5
    ]);
    if (empty($tweets)) {
      return;
    }
    \Drupal::state()->set('msca_tweet_block_tweet', array_shift($tweets));
    \Drupal\Core\Cache\Cache::invalidateTags(['msca_tweet_block']);
  }
  catch (\Exception $exception) {
    watchdog_exception('msca_tweet_block', $exception);
    \Drupal::logger('msca_tweet_block')->error('Unable to retrieve recent tweets: %msg',
      ['%msg' => $exception->getMessage()]);
  }

}

/**
 * Implements hook_theme().
 */
function msca_tweet_block_theme() {
  return [
    'msca_tweet_block' => [
      'variables' => [
        'time_ago' => null,
        'text' => null,
        'retweets' => null,
        'favs' => null,
        'twitter_url' => null,
        'facebook_url' => null,
      ]
    ]
  ];
}
