id: forward_settings
label: Forward configuration
migration_tags:
  - Drupal 6
  - Drupal 7
source:
  plugin: variable
  variables:
    - forward_filter_html
    - forward_filter_tags
    - forward_flood_control
    - forward_link_noindex
    - forward_message
process:
  forward_personal_message_filter: forward_filter_html
  forward_personal_message_tags: forward_filter_tags
  forward_flood_control_limit: forward_flood_control
  forward_form_noindex: forward_link_noindex
  forward_personal_message: forward_message
destination:
  plugin: config
  config_name: forward.settings
