<?php

/**
 * @file
 * Contains msca_events.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function msca_events_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the msca_events module.
    case 'help.page.msca_events':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides functionality related to the education_events content type.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param string $form_id
 * @return void
 */
function msca_events_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $node = $form_state->getformObject()->getEntity();
  if ($node->getType() !== 'education_events') {
    return;
  }

  // Add a validation function.
  $form['#validate'][] = 'msca_events_validate';

  // Add a submit function.
  array_unshift($form['actions']['submit']['#submit'], 'msca_events_submit');

  $form['field_location']['#prefix'] = '<div id="field_location_ajax_wrapper">';
  $form['field_location']['#suffix'] = '</div>';

  $form['field_location']['#states'] = [
    'visible' => [
      '#edit-field-virtual-event-value' => [
        'checked' => FALSE,
      ],
    ],
  ];
}

/**
 * Validation function for education_events node form.
 *
 * @param array $form
 * @param FormStateInterface $form_state
 * @return void
 */
function msca_events_validate(&$form, FormStateInterface $form_state) {
  $virtual = $form_state->getValue('field_virtual_event')['value'];
  if (!$virtual) {
    $country = $form_state->getValue('field_location')[0]['address']['country_code'];
    if ($country == "") {
      $form_state->setErrorByName('field_location', 'Events that are not virtual must have a location. Please select United States from the country field and complete the address.');
    }
  }
}

/**
 * Submit function for education_events node form.
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @return void
 */
function msca_events_submit($form, FormStateInterface $form_state) {
  $virtual = $form_state->getValue('field_virtual_event')['value'];
  if ($virtual) {
    $default_value = [
      'langcode' => NULL,
      'country_code' => NULL,
      'administrative_area' => NULL,
      'locality' => NULL,
      'dependent locality' => NULL,
      'postal_code' => NULL,
      'sorting_code' => NULL,
      'address_line1' => NULL,
      'address_line2' => NULL,
      'organization' => NULL,
      'given_name' => NULL,
      'additional_name' => NULL,
      'family_name' => NULL,
    ];
    $form_state->setValue('field_location', [['address' => $default_value]]);
  }
}
