real_magnet:
  real_magnet_username: ''
  real_magnet_password: ''
  real_magnet_template_id: ''
  real_magnet_login_id: ''
_core:
  default_config_hash: In-CGtGxRgWnohc0JWH6ZiY9G2zjuUL-1o9o0LZNMXU
real_magnet_username: anne@bluecoda.com
real_magnet_password: bluecoda1
real_magnet_template_id: '143'
real_magnet_login_id: '70148'
