# Schema for the configuration files of the Forward module.
forward.settings:
  type: config_object
  label: 'Forward settings'
  mapping:
    forward_form_title:
      type: label
      label: 'Page title of Forward page'
    forward_form_noindex:
      type: boolean
      label: 'No-index'
    forward_max_recipients:
      type: integer
      label: 'Maximum recipients'
    forward_form_instructions:
      type: label
      label: 'Instructions'
    forward_form_allow_plain_text:
      type: boolean
      label: 'Allow plain text'
    forward_form_display_page:
      type: boolean
      label: 'Display page'
    forward_form_display_subject:
      type: boolean
      label: 'Display message subject'
    forward_form_display_body:
      type: boolean
      label: 'Display message body'
    forward_personal_message:
      type: integer
      label: 'Display personal message'
    forward_personal_message_filter:
      type: boolean
      label: 'Allow HTML'
    forward_personal_message_tags:
      type: string
      label: 'Allowed HTML tags'
    forward_form_confirmation:
      type: label
      label: 'Confirmation message'
    forward_email_logo:
      type: string
      label: 'Path to custom logo'
    forward_email_from_address:
      type: string
      label: 'Email from address'
    forward_email_subject:
      type: label
      label: 'Email subject line'
    forward_email_message:
      type: label
      label: 'Email message header'
    forward_email_footer:
      type: label
      label: 'Email message footer'
    forward_bypass_access_control:
      type: integer
      label: 'Bypass access control'
    forward_filter_format_html:
      type: string
      label: 'HTML filter format'
    forward_filter_format_plain_text:
      type: string
      label: 'Plain text filter format'
    forward_flood_control_limit:
      type: integer
      label: 'Flood control limit'
    forward_flood_control_error:
      type: label
      label: 'Flood control error message'

field.formatter.settings.forward_link:
  type: mapping
  label: 'Forward link formatter display settings'
  mapping:
    title:
      type: string
      label: 'Link title'
    style:
      type: integer
      label: 'Link style'
    icon:
      type: string
      label: 'Path to custom icon'
    nofollow:
      type: boolean
      label: 'No-follow'
